version: 2
jobs:
  build:
    working_directory: ~/circleci-demo-ruby-rails
    
    # Primary container image where all commands run
    
    docker:
      - image: cmosh/lambda-mssql:python3.7
        environment:
          DB_SERVER: 127.0.0.1
          DB_PORT: 1433
          DB_NAME: yebo
          DB_USER: sa
          DB_PASS: 'Str0ng!Pass'
    
    # Service container image available at `host: localhost`
    
      - image: mcr.microsoft.com/mssql/server
        environment:
          ACCEPT_EULA: 'Y'
          SA_PASSWORD: 'Str0ng!Pass'
        
    steps:
      - checkout

      - run:
          name: Install dependencies
          command: pip install -r requirements.txt

      - run:
          name: Database Setup
          command: | 
            /opt/mssql-tools/bin/sqlcmd -S $DB_SERVER -U $DB_USER -P $DB_PASS -i sql/schema.sql
            /opt/mssql-tools/bin/sqlcmd -S $DB_SERVER -U $DB_USER -P $DB_PASS -i sql/seed.sql
            
      - run:
          name: Test Lambda
          command: |-
            unzip layers/pyodbc-layer.zip -d /opt/
            rm -rf /var/task
            ln -s $PWD /var/task
            /var/rapid/init --bootstrap /var/runtime/bootstrap yebo.app '{"some": "event"}'
